config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :lists, only: %i[index show new create destroy] do
    resources :bookmarks, only: %i[index new create]
  end

  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie, dependent: :destroy
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "Bookmark already exists for this movie and list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true
  validates :title, :overview, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: %i[new create]

  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show ]
  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
 <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.input :comment %>
      <%= f.association :movie%>
      <%= f.submit %>
    <% end %>

app/views/bookmarks/new.html.erb
 <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.association :movie%>
      <%= f.input :comment%>
      <%= f.submit %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<div class="container">
  <h1>My lists</h1>
  <%= link_to "Create a movie list", new_list_path %>
  <br>
  <ul>
    <% @lists.each do |list| %>
      <%= link_to list.name, list_path(list) %>
    <% end %>
  </ul>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>New list</h1>

  <%= render 'form' %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h1 class="m-0"><%= @list.name %></h1>

    <%= link_to "Add movie", new_list_bookmark_path(@list), class: "btn btn-warning" %>
  </div>

  <div class="movie-cards row mb-5">
    <% @list.movies.each do |movie| %>
      <div class="movie-card border col-6">
        <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
        <p class="m-0"><%= movie.title %></p>
        <p><%= bookmark.comment %></p>
      </div>
    <% end %>
  </div>


  <h1>Add another movie</h1>
  <%= render "bookmarks/form" %>


  <%= link_to "Back to List", root_path %>

</div>